In [1]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:

df = pd.read_csv("students.csv")

print("Original Dataset:")
display(df)

FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'

In [3]:
df = pd.read_csv("students.csv")

print("Original Dataset:")
display(df)

Original Dataset:

    name  age  score
0  Abebe   20   85.0
1   Sara   19   92.0
2   Mimi   21   78.0
3  Dawit   20   65.0
4   Hana   19   88.0
5   Sara   19   92.0
6  Robel   22    NaN
7   Liya   20  120.0

In [4]:
def clean_data(df):
    # Remove duplicate rows
    df = df.drop_duplicates()

    # Convert score values to numbers
    df["score"] = pd.to_numeric(df["score"], errors="coerce")

    # Treat scores outside 0–100 as invalid
    df.loc[~df["score"].between(0, 100), "score"] = np.nan

    # Fill missing scores with the median of valid scores
    median_score = df["score"].median()
    df["score"] = df["score"].fillna(median_score)

    return df


cleaned_df = clean_data(df.copy())

print("Cleaned Dataset:")
display(cleaned_df)

Cleaned Dataset:

    name  age  score
0  Abebe   20   85.0
1   Sara   19   92.0
2   Mimi   21   78.0
3  Dawit   20   65.0
4   Hana   19   88.0
6  Robel   22   85.0
7   Liya   20   85.0

In [5]:
# Get the scores as a NumPy array
scores = cleaned_df["score"].to_numpy()

# Calculate statistics using NumPy
average = np.mean(scores)
highest = np.max(scores)
lowest = np.min(scores)
standard_deviation = np.std(scores)

print("Student Score Analysis")
print("----------------------")
print("Average Score:", round(average, 2))
print("Highest Score:", highest)
print("Lowest Score:", lowest)
print("Standard Deviation:", round(standard_deviation, 2))

Student Score Analysis
----------------------
Average Score: 82.57
Highest Score: 92.0
Lowest Score: 65.0
Standard Deviation: 8.16

In [6]:
cleaned_df.to_csv("cleaned_students.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!